package codegen

// WrapperTemplate is the template for generated wrapper functions
const WrapperTemplate = `// Code generated by lcc-codegen. DO NOT EDIT.

package {{.Package}}

import (
	"fmt"
	"log"
	
	"github.com/yourorg/lcc-sdk/pkg/client"
)

var (
	_lccClient *client.Client
	_lccInitialized bool
)

// _lccInit initializes the LCC client (called automatically)
func _lccInit() error {
	if _lccInitialized {
		return nil
	}
	
	// TODO: Load from config file
	// For now, this will be set by the application
	if _lccClient == nil {
		return fmt.Errorf("LCC client not initialized")
	}
	
	_lccInitialized = true
	return nil
}

// SetLCCClient sets the LCC client for this package
func SetLCCClient(client *client.Client) {
	_lccClient = client
	_lccInitialized = true
}

{{range .Functions}}
// {{.OriginalName}}_Original is the original implementation
var {{.OriginalName}}_Original = {{.OriginalName}}

// {{.OriginalName}} is the license-protected wrapper
{{.Signature}} {
	// Check license
	if _lccClient != nil {
		status, err := _lccClient.CheckFeature("{{.FeatureID}}")
		if err != nil {
			log.Printf("[LCC] Feature check failed for {{.FeatureID}}: %v", err)
			{{if .HasFallback}}
			// Use fallback
			{{.FallbackCall}}
			{{else}}
			{{.ErrorReturn}}
			{{end}}
		}
		
		if status != nil && !status.Enabled {
			log.Printf("[LCC] Feature {{.FeatureID}} not enabled: %s", status.Reason)
			{{if .HasFallback}}
			// Use fallback
			{{.FallbackCall}}
			{{else}}
			{{.ErrorReturn}}
			{{end}}
		}
		
		// Report usage
		go func() {
			_ = _lccClient.ReportUsage("{{.FeatureID}}", 1.0)
		}()
	}
	
	// Call original function
	{{.OriginalCall}}
}
{{end}}
`

// FunctionTemplate represents a function to be wrapped
type FunctionTemplate struct {
	OriginalName string
	Signature    string
	FeatureID    string
	HasFallback  bool
	FallbackCall string
	ErrorReturn  string
	OriginalCall string
}

// PackageTemplate represents the data for generating a package
type PackageTemplate struct {
	Package   string
	Functions []FunctionTemplate
}
